Update kubectl-commands

diff --git a/kubeadm-ubuntu-rrk/kubectl-commands b/kubeadm-ubuntu-rrk/kubectl-commands
--- a/kubeadm-ubuntu-rrk/kubectl-commands
+++ b/kubeadm-ubuntu-rrk/kubectl-commands
@@ -236,3 +236,10 @@ kubectl create secret generic sec --from-file=ssh-private=/root/.ssh/known_hosts
 
 kubectl create secret generic sec --from-file=usercred=ravikiran --from-literal=passphrase=ravikiran300 --dry-run=client -o yaml
 
+=================================================
+
+for i in {1..35}; do
+   kubectl exec --namespace=kube-public curl -- sh -c 'test=`wget -qO- -T 2  http://webapp-service.default.svc.cluster.local:8080/info 2>&1` && echo "$test OK" || echo "Failed"';
+   echo ""
+done
+
